In [1]:
import pypsa

In [2]:
n = pypsa.Network("../../../pypsa-earth/results/prenetworks/elec_s_14_ec_lcopt_Co2L0.0-3H_3H_2050_0.071_AB_10export.nc")

WARNING:pypsa.io:Importing network from PyPSA version v0.28.0 while current version is v0.30.3. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.io:Imported network elec_s_14_ec_lcopt_Co2L0.0-3H_3H_2050_0.071_AB_10export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [ ]:
n = pypsa.Network("../../../pypsa-earth/results/postnetworks/elec_s_14_ec_lcopt_Co2L0.0-3H_3H_2050_0.071_AB_10export.nc")

INFO:pypsa.io:Imported network elec_s_14_ec_lcopt_Co2L0.0-3H_3H_2050_0.071_AB_10export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [ ]:
n.generators[n.generators.carrier == "H2O"]

,carrier,bus,p_nom_min,p_nom,p_nom_extendable,marginal_cost,capital_cost,p_nom_max,weight,control,...,shut_down_cost,stand_by_cost,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down
Generator,,,,,,,,,,,,,,,,,,,,,
NA.10_1_AC H20-2050,H2O,NA.10_1_AC H2O,0.0,0.0,True,0.010801,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.11_1_AC H20-2050,H2O,NA.11_1_AC H2O,0.0,0.0,True,0.009598,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.12_1_AC H20-2050,H2O,NA.12_1_AC H2O,0.0,0.0,True,0.009850,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.1_1_AC H20-2050,H2O,NA.1_1_AC H2O,0.0,0.0,True,0.010588,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.2_1_AC H20-2050,H2O,NA.2_1_AC H2O,0.0,0.0,True,0.010107,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.3_1_AC H20-2050,H2O,NA.3_1_AC H2O,0.0,0.0,True,0.009365,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.4_1_AC H20-2050,H2O,NA.4_1_AC H2O,0.0,0.0,True,0.009941,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.5_1_AC H20-2050,H2O,NA.5_1_AC H2O,0.0,0.0,True,0.010440,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.7_1_AC H20-2050,H2O,NA.7_1_AC H2O,0.0,0.0,True,0.010785,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.8_1_AC H20-2050,H2O,NA.8_1_AC H2O,0.0,0.0,True,0.010204,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.9_1_AC H20-2050,H2O,NA.9_1_AC H2O,0.0,0.0,True,0.009133,0.0,inf,1.0,PQ,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0

In [ ]:
n.links[n.links.carrier == "H2 Electrolysis"]

,bus0,bus1,carrier,p_nom_extendable,efficiency,capital_cost,bus2,bus3,bus4,efficiency2,...,start_up_cost,shut_down_cost,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down
Link,,,,,,,,,,,,,,,,,,,,,
NA.10_1_AC H2 Electrolysis-2050,NA.10_1_AC,NA.10_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.10_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.11_1_AC H2 Electrolysis-2050,NA.11_1_AC,NA.11_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.11_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.12_1_AC H2 Electrolysis-2050,NA.12_1_AC,NA.12_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.12_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.1_1_AC H2 Electrolysis-2050,NA.1_1_AC,NA.1_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.1_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.2_1_AC H2 Electrolysis-2050,NA.2_1_AC,NA.2_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.2_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.3_1_AC H2 Electrolysis-2050,NA.3_1_AC,NA.3_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.3_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.4_1_AC H2 Electrolysis-2050,NA.4_1_AC,NA.4_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.4_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.5_1_AC H2 Electrolysis-2050,NA.5_1_AC,NA.5_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.5_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.7_1_AC H2 Electrolysis-2050,NA.7_1_AC,NA.7_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.7_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.8_1_AC H2 Electrolysis-2050,NA.8_1_AC,NA.8_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.8_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0
NA.9_1_AC H2 Electrolysis-2050,NA.9_1_AC,NA.9_1_AC H2,H2 Electrolysis,True,0.6994,125810.517221,NA.9_1_AC H2O,,,-211.939394,...,0.0,0.0,0,0,1,0,NaN,NaN,1.0,1.0

In [ ]:
n.statistics.energy_balance().loc[:,:,"H2"]

component  carrier
Generator  load                        1.095968e+03
Link       Fischer-Tropsch            -1.570504e+00
           H2 Electrolysis             1.030063e+07
           H2 Fuel Cell               -1.245548e+00
           Sabatier                   -1.602704e+00
Store      H2 Store Tank               9.684926e-13
Load       H2                         -1.000000e+07
           H2 for shipping            -8.332163e+03
           land transport fuel cell   -2.933876e+05
dtype: float64

In [ ]:
n.links[n.links.carrier == "H2"].p_set

Link
NA.1_1_AC H2 export    0.0
NA.2_1_AC H2 export    0.0
Name: p_set, dtype: float64

In [ ]:
n.statistics.energy_balance(comps=["Generator"]).loc[:,"load",:].div(1e3)

component  bus_carrier
Generator  AC                                         0.000055
           H2                                         1.095968
           Li ion                                     0.000075
           battery                                    0.000055
           biogas                                     0.000070
           co2 stored                                 0.000065
           home battery                               0.000057
           low voltage                                0.027298
           process emissions                          0.000006
           residential rural heat                     0.000100
           residential rural water tanks              0.000057
           residential urban decentral heat           0.000053
           residential urban decentral water tanks    0.000069
           services rural heat                        0.000053
           services rural water tanks                 0.000069
           services urban decentral heat              0.000055
           services urban decentral water tanks       0.000054
           urban central heat                         0.000054
           urban central water tanks                  0.000054
Name: generators, dtype: float64

In [ ]:
df = n.statistics.energy_balance(comps=["Link"]).droplevel(0)

In [ ]:
filtered_df = df[df.index.get_level_values('carrier').str.contains('H2') | df.index.get_level_values('bus_carrier').str.contains('H2')]

# Display the filtered DataFrame
print(filtered_df)

carrier          bus_carrier
Fischer-Tropsch  H2            -1.570504e+00
H2 Electrolysis  AC            -1.472781e+07
                 H2             1.030063e+07
                 H2O           -3.121402e+09
H2 Fuel Cell     AC             6.227742e-01
                 H2            -1.245548e+00
Sabatier         H2            -1.602704e+00
Name: objective, dtype: float64

In [ ]:
df = n.statistics.energy_balance(comps=["Generator"]).droplevel(0)

In [ ]:
filtered_df = df[df.index.get_level_values('carrier').str.contains('H2') | df.index.get_level_values('bus_carrier').str.contains('H2')]

# Display the filtered DataFrame
print(filtered_df)

carrier  bus_carrier
H2O      H2O            3.121402e+09
load     H2             1.095968e+03
Name: generators, dtype: float64

In [ ]:
df = n.statistics.market_value(comps=["Link"])
print(df[df.index.get_level_values('carrier').str.contains('H2')])

WARNING:pypsa.statistics:Network has multiple bus carriers which are aggregated together. To separate bus carriers set `bus_carrier` or use groupers like `get_carrier_and_bus_carrier`.

component  carrier
Link       H2                  0.009891
           H2 Electrolysis    25.029459
           H2 Fuel Cell      -91.083200
           H2 pipeline         1.472757
Name: objective, dtype: float64

In [ ]:
n.loads[n.loads.carrier.str.contains('H2')]

,bus,carrier,p_set,type,q_set,sign
Load,,,,,,
NA.10_1_AC H2 for industry,NA.10_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.11_1_AC H2 for industry,NA.11_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.12_1_AC H2 for industry,NA.12_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.1_1_AC H2 for industry,NA.1_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.2_1_AC H2 for industry,NA.2_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.3_1_AC H2 for industry,NA.3_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.4_1_AC H2 for industry,NA.4_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.5_1_AC H2 for industry,NA.5_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.7_1_AC H2 for industry,NA.7_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.8_1_AC H2 for industry,NA.8_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.9_1_AC H2 for industry,NA.9_1_AC H2,H2 for industry,0.00000,,0.0,-1.0
NA.10_1_AC H2 for shipping,NA.10_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.11_1_AC H2 for shipping,NA.11_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.12_1_AC H2 for shipping,NA.12_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.1_1_AC H2 for shipping,NA.1_1_AC H2,H2 for shipping,0.47558,,0.0,-1.0
NA.2_1_AC H2 for shipping,NA.2_1_AC H2,H2 for shipping,0.47558,,0.0,-1.0
NA.3_1_AC H2 for shipping,NA.3_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.4_1_AC H2 for shipping,NA.4_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.5_1_AC H2 for shipping,NA.5_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.7_1_AC H2 for shipping,NA.7_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.8_1_AC H2 for shipping,NA.8_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
NA.9_1_AC H2 for shipping,NA.9_1_AC H2,H2 for shipping,0.00000,,0.0,-1.0
H2 export load,H2 export bus,H2,0.00000,,0.0,-1.0

In [ ]:
n.loads_t.p[n.loads[n.loads.carrier.str.contains('H2')]]

Load,H2 export load,NA.10_1_AC,NA.10_1_AC H2 for industry,NA.10_1_AC H2 for shipping,NA.10_1_AC agriculture electricity,NA.10_1_AC agriculture oil,NA.10_1_AC gas for industry,NA.10_1_AC industry electricity,NA.10_1_AC kerosene for aviation,NA.10_1_AC land transport EV,...,agriculture oil emissions,aviation oil emissions,industry coal emissions,industry oil emissions,land transport oil emissions,residential gas emissions,residential oil emissions,services gas emissions,services oil emissions,shipping oil emissions
snapshot,,,,,,,,,,,,,,,,,,,,,
2013-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-01 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-01 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-31 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-12-31 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-12-31 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-12-31 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-12-31 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN